import './globals.css'
import Topbar from './topbar/page'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <Topbar/>
      {children}
      </body>
    </html>
  )
}
